package com.sb.factorium;

import java.util.List;
import java.util.Map;
import java.util.Vector;

/**
 * A RecordingFactory is a factory that keeps an accessible record of everything it has created.
 *
 * @param <T> the type of objects generated by this factory.
 */
public class RecordingFactory<K, T> extends BaseFactory<K, T> {

    protected List<T> created;

    public RecordingFactory(K defaultKey, Map<K, Generator<T>> generators) {
        super(defaultKey, generators);
        this.created = new Vector<>();
    }

    @Override
    protected void decorate(T newItem, Modifier[] modifiers) {
        created.add(newItem);
    }

    @Override
    protected void decorate(List<T> newItems, Modifier[] modifiers) {
        created.addAll(newItems);
    }

    public List<T> getCreated() {
        return created;
    }
}
